name: CI/CD para Elastic Beanstalk

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}                 
  EB_APPLICATION: product-api                  
  EB_ENVIRONMENT: Product-api-env                

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout do código
        uses: actions/checkout@v4                          

      
      - name: Setup Java
        uses: actions/setup-java@v4                         
        with:
          distribution: 'temurin'
          java-version: '21'

   
      - name: Build com Maven
        run: mvn clean package -DskipTests               

  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1        
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

   
      - name: Deploy para Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22         
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.EB_APPLICATION }}
          environment_name: ${{ env.EB_ENVIRONMENT }}
          version_label: ${{ github.run_number }}-$(date +%s)
          region: ${{ env.AWS_REGION }}
          deployment_package: target/product-api.jar
